#!/bin/bash

echo updating apt-get
sudo apt-get -y update >/dev/null
echo installing git-core
sudo apt-get -y install curl git-core >/dev/null
echo installing some global dependencies
sudo apt-get -y install build-essential wget libreadline-dev libncurses5-dev libssl1.0.0 tk8.5-dev zlib1g-dev liblzma-dev >/dev/null
echo installing pyenv with pyenv-installer
sudo curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash >/dev/null
echo making sure the .pyenv file has proper permissions
sudo chmod 777 /home/vagrant/.pyenv
echo adding some things to .bashrc related to pyenv
cat /vagrant/bashrc >> ~/.bashrc
echo sourcing .bashrc to make changes take effect
source ~/.bashrc

declare -a python_versions=(
	"3.4.1"
	)

	# stuff we support, feel free to add these to the above list
	# "2.6.6"
	# "2.6.7"
	# "2.6.8"
	# "2.6.9"
	# "2.7"
	# "3.2"
	# "3.3.0"
	# "3.3.1"
	# "3.3.2"
	# "3.3.3"
	# "3.3.4"
	# "3.3.5"
	# "3.4.0"
	# "3.4.1"

echo about to install these:
for i in "${python_versions[@]}"
do
	echo $i
done

echo ""

for i in "${python_versions[@]}"
do
	echo $i
	echo "installing python$i build dependencies"
	sudo apt-get -y build-dep "python${i:0:3}" >/dev/null
	echo "installing python $i with pyenv"
	pyenv install "$i" -v > "install-$i.log"
	export PYENV_VERSION="$i"
	echo installing nose for testing
	pip install nose >/dev/null
	echo installing core requirements
	pip install -r /home/python-api/requirements.txt >/dev/null
	echo installing matplotlib dependencies
	sudo apt-get -y build-dep python-matplotlib >/dev/null
	echo installing matplotlib
	pip install matplotlib >/dev/null
	if [ "${i:0:3}" == "2.6" ]
		then
			pip install ordereddict
			pip install simplejson
	fi
	echo ""

echo "what i wanted to install:"
echo about to install these:
for i in "${python_versions[@]}"
do
	echo $i
done
echo ""
echo "what i installed:"
pyenv versions
