#!/bin/bash

declare -a python_versions=(
	"3.4.1"
	)

	# stuff we support, feel free to add these to the above list
	# "2.6.6"
	# "2.6.7"
	# "2.6.8"
	# "2.6.9"
	# "2.7"
	# "3.2"
	# "3.3.0"
	# "3.3.1"
	# "3.3.2"
	# "3.3.3"
	# "3.3.4"
	# "3.3.5"
	# "3.4.0"

rm test_log.txt >/dev/null
touch test_log.txt

for i in "${python_versions[@]}"
do
	echo $i; echo ""; echo ""
	echo $i >>test_log.txt 2>&1
	echo "=====" >>test_log.txt 2>&1
	echo "" >>test_log.txt 2>&1
	export PYENV_VERSION="$i"
	pip uninstall -y plotly >/dev/null
	# pip install -I /home/python-api >/dev/null
	pip install plotly >/dev/null
	echo testing >>test_log.txt 2>&1
	nosetests -w /home/python-api/plotly/tests >>test_log.txt 2>&1
	echo "" >>test_log.txt 2>&1
	echo "" >>test_log.txt 2>&1
done

cp test_log.txt /vagrant/test_log.txt
